<?php
/**
 * Icon Helper for Admin CMS
 * Returns a list of Bootstrap Icons
 */

function icon_get_list()
{
    // A curated list of common useful icons to avoid overwhelming the user
    // In a real app, this could be parsed from the CSS file
    return [
        // Basics & Actions
        'bi-star',
        'bi-star-fill',
        'bi-heart',
        'bi-heart-fill',
        'bi-check',
        'bi-check-circle',
        'bi-check-circle-fill',
        'bi-x',
        'bi-x-circle',
        'bi-x-circle-fill',
        'bi-info-circle',
        'bi-info-circle-fill',
        'bi-exclamation-circle',
        'bi-exclamation-triangle',
        'bi-gear',
        'bi-gear-fill',
        'bi-person',
        'bi-person-fill',
        'bi-people',
        'bi-people-fill',
        'bi-envelope',
        'bi-envelope-fill',
        'bi-telephone',
        'bi-telephone-fill',
        'bi-geo-alt',
        'bi-geo-alt-fill',
        'bi-calendar',
        'bi-calendar-event',
        'bi-clock',
        'bi-clock-fill',
        'bi-search',
        'bi-funnel',
        'bi-funnel-fill',

        // Symbols & Objects
        'bi-lightning',
        'bi-lightning-fill',
        'bi-rocket',
        'bi-rocket-takeoff',
        'bi-shield',
        'bi-shield-fill',
        'bi-gem',
        'bi-trophy',
        'bi-trophy-fill',
        'bi-gift',
        'bi-gift-fill',
        'bi-hand-thumbs-up',
        'bi-hand-thumbs-up-fill',
        'bi-patch-check',
        'bi-patch-check-fill',
        'bi-mortarboard',
        'bi-mortarboard-fill',
        'bi-piggy-bank',
        'bi-piggy-bank-fill',
        'bi-wallet2',
        'bi-credit-card',
        'bi-credit-card-fill',
        'bi-cash-stack',
        'bi-bank',
        'bi-bag',
        'bi-bag-fill',
        'bi-cart',
        'bi-cart-fill',

        // Tech & Media
        'bi-app-indicator',
        'bi-arrow-repeat',
        'bi-cloud-arrow-down',
        'bi-cloud-arrow-up',
        'bi-display',
        'bi-laptop',
        'bi-phone',
        'bi-tablet',
        'bi-smartwatch',
        'bi-cpu',
        'bi-gpu-card',
        'bi-keyboard',
        'bi-mouse',
        'bi-printer',
        'bi-image',
        'bi-camera',
        'bi-play-circle',
        'bi-play-circle-fill',
        'bi-pause-circle',
        'bi-stop-circle',
        'bi-volume-up',
        'bi-volume-mute',
        'bi-mic',
        'bi-mic-fill',
        'bi-music-note-beamed',
        'bi-film',
        'bi-headset',

        // Communication & Social
        'bi-chat',
        'bi-chat-dots',
        'bi-chat-fill',
        'bi-share',
        'bi-reply',
        'bi-send',
        'bi-send-fill',
        'bi-megaphone',
        'bi-megaphone-fill',
        'bi-bell',
        'bi-bell-fill',
        'bi-globe',
        'bi-translate',
        'bi-apple',
        'bi-android2',
        'bi-windows',
        'bi-facebook',
        'bi-instagram',
        'bi-twitter-x',
        'bi-github',
        'bi-linkedin',
        'bi-whatsapp',
        'bi-telegram',
        'bi-discord',
        'bi-youtube',
        'bi-google',
        'bi-wordpress',

        // Interface & Navigation
        'bi-list',
        'bi-grid',
        'bi-three-dots',
        'bi-three-dots-vertical',
        'bi-plus',
        'bi-plus-circle',
        'bi-dash',
        'bi-dash-circle',
        'bi-arrow-left',
        'bi-arrow-right',
        'bi-arrow-up',
        'bi-arrow-down',
        'bi-chevron-left',
        'bi-chevron-right',
        'bi-chevron-up',
        'bi-chevron-down',
        'bi-box-arrow-in-right',
        'bi-box-arrow-right',
        'bi-download',
        'bi-upload',
        'bi-link',
        'bi-link-45deg',
        'bi-paperclip',
        'bi-trash',
        'bi-trash-fill',
        'bi-pencil',
        'bi-pencil-square',
        'bi-save',

        // Business & Stats
        'bi-briefcase',
        'bi-briefcase-fill',
        'bi-graph-up',
        'bi-graph-down',
        'bi-pie-chart',
        'bi-kanban',
        'bi-journal-text',
        'bi-file-earmark-text',
        'bi-folder',
        'bi-folder-fill',
        'bi-speedometer',
        'bi-speedometer2',
        'bi-activity',
        'bi-layers',
        'bi-stack',
        'bi-puzzle',
        'bi-hammer',
        'bi-wrench-adjustable',
        'bi-tools',

        // Weather & Nature
        'bi-sun',
        'bi-sun-fill',
        'bi-moon',
        'bi-moon-stars',
        'bi-cloud-sun',
        'bi-cloud-moon',
        'bi-cloud-rain',
        'bi-cloud-snow',
        'bi-wind',
        'bi-water',
        'bi-fire',
        'bi-tree',

        // Security & Law
        'bi-lock',
        'bi-lock-fill',
        'bi-unlock',
        'bi-unlock-fill',
        'bi-key',
        'bi-key-fill',
        'bi-pass',
        'bi-shield-check',
        'bi-shield-lock',

        // Health & Education
        'bi-heart-pulse',
        'bi-hospital',
        'bi-capsule',
        'bi-thermometer-half',
        'bi-book',
        'bi-book-fill',
        'bi-mortarboard',
        'bi-mortarboard-fill',

        // Food & Life
        'bi-cup-hot',
        'bi-cup-straw',
        'bi-egg-fried',
        'bi-house',
        'bi-house-fill',
        'bi-building',
        'bi-car-front',
        'bi-bicycle',
        'bi-universal-access'
    ];
}
?>